### ISSUE TITLE
tracking: DevTools support

### ISSUE THREAD

**Issue by marc2332** [marc2332/freya#16]
This issue tracks the support for DevTools.

To enable DevTools, simply run Freya with the `devtools` feature.

At the moment, it only integrates a Node Tree Inspector:

![image](https://user-images.githubusercontent.com/38158676/193324807-7f726913-a6ce-4baa-b498-1fb3c368e5d5.png)

Some ideas:
- [ ] Being able to highlight an element in the actual app by simply clicking on the Node from the Nodes Tree
- [ ] Inspect a Node size, style, etc.
- [ ] Inspect a Node event listeners
