### ISSUE TITLE
tracking: Layout

### ISSUE THREAD

**Issue by marc2332** [marc2332/freya#225]
This tracks the support for layout features.

- [x] Width
- [x] Height
- [x] Minimum width
- [x] Minimum height
- [x] Paddings
- [x] Stacking directions (vertical and horizontal)
- [x] Custom `x` and `y` offsets relative to the parent
- [x] Margins
- [x] Main and Cross axis alignment
- [x] Absolute positioning
