### ISSUE TITLE
tracking: Scrolling improvements

### ISSUE THREAD

**Issue by tropicaaal** [marc2332/freya#264]
Keyboard Interaction
- [x] Arrow keys (#263)
- [x] <kbd>PageUp</kbd>/<kbd>PageDown</kbd> (#263)
- [x] <kbd>Home</kbd>/<kbd>End</kbd> (#263)
- [ ] ~~<kbd>Space</kbd>/<kbd>Shift</kbd>+<kbd>Space</kbd> (unsure)~~
- [x] <kbd>Alt</kbd> to increase scroll velocity (#263)

Mouse/Wheel Interaction
- [x] Dragging Scrollbar thumbs
- [x] Clicking/holding outside of thumbs
- [ ] ~~(possibly, maybe not) Optional Buttons~~
- [x] Basic Wheel Scrolling (constant velocity with multiplier)
- [x] Wheel event bubbling 
- [ ] Kinetic Scrolling (simulated physics for velocity/acceleration, required for touch integration)
- [ ] ~~Overscroll behavior (bouncing or stretching effect seen on iOS/Android)~~

Touch Interaction
- [ ] General Support

General Accessibility
- [x] Accessible roles
- [x] Scroll to focused item (#1275)
- [x] Scroll progress reporting (#1275)

Styling
- [x] Colors
- [x] Hide scrollbars

**Comment by marc2332** [comment]
As of now, what is missing is touch support, I might close this issue and open a new one

**Comment by marc2332** [comment]
Closing in favor of https://github.com/marc2332/freya/issues/1469
