### ISSUE TITLE
tracking: Components library 

### ISSUE THREAD

**Issue by marc2332** [marc2332/freya#4]
Tracking the implementation of the [components](https://github.com/marc2332/freya/tree/main/crates/components/src) library:

- Switch
    - [x] Implemented
- Button
    - [x] Implemented
    - [x] Partial Accessibility
- Slider
    - [x] Implemented
- Input
    - [x] Implemented
    - [x] Cursor support
- ScrollView
    - [x] Implemented
    - [x] show_scrollbar
    - [x] Vertical direction
    - [x] Horizontal direction
    - [x] Both directions
    - [ ] Scroll events
    - [ ] Custom Scrollbar component
- VirtualScrollView
    - [x] Implemented
    - [x] Vertical direction
    - [x] Horizontal direction
    - [ ] Scroll events
    - [ ] Custom Scrollbar component
- LocalImage
    - [ ] Implemented (https://github.com/marc2332/freya/issues/111)
- NetworkImage
    - [x] Implemented
    - [x] Partial Accessibility
- Dropdown
    - [x] Implemented
    - [x] Partial Accessibility
    - [ ] Multiselect
- Accordion
    - [x] Implemented
    - [ ] Group-awareness ([example](https://jqueryui.com/accordion/))
- GestureArea
    - [x] Implemented
    - [x] TapUp
    - [x] TapDown
    - [x] DoubleTap
    - [ ] LongPress
    - [ ] Drag
- Drag & Drop
    - [x] Implemented
    - [x] DragZone
    - [x] DropZone
- CursorArea 
    - [x] Implemented
- Graph
    - [x] Implemented
    - [ ] Customizable
 - Table
    - [x] Implemented
 - ProgressBar
    - [x] Implemented

**Comment by Mingun** [comment]
The link to components is outdated, correct one is https://github.com/marc2332/freya/tree/main/crates/components/src. Also, what about a tree widget component?

**Comment by marc2332** [comment]
> The link to components is outdated, correct one is https://github.com/marc2332/freya/tree/main/crates/components/src.

Nice catch, just fixed it!

>  Also, what about a tree widget component?
A tree widget is an interesting idea but I feel like that is a very complex component to be included by default, I don't know, what do you have in mind?

**Comment by Mingun** [comment]
Tree view is a very flexible component that is needed in many GUI applications. For example, I would like to use it to:
- show properties in property sheets
- show hierarchy of objects where children can inherit properties from parent
- show nested objects, for example, a list of spans after parsing of a file by a grammar

Have freya some ideas how it would be implemented if not in core, but by the user itself? What building blocks should be used, how to implement it effectively? Assume that I have a hundreds of nodes in a memory and I want to show them as a tree. Qt and Swing have nice abstractions of tree models, that streams only necessary data to tree view, how implement the same in freya? Any guidelines?
