### ISSUE TITLE
tracking: Styling

### ISSUE THREAD

**Issue by marc2332** [marc2332/freya#46]
Tracks styling attributes and features.

## Text elements

- [x] Color
- [x] Font size
- [x] Font style
- [x] Built-in Font family
- [x] Custom fonts 
- [x] Text decorations
- [x] Text align
- [x] Text max lines
- [x] Font style
- [x] Font weight
- [x] Font width
- [x] Text shadow
- [x] Letter spacing
- [x] Word spacing 
- [x] `linear-gradient()`
- [x] `rgb()`
- [x] `hsl()`

## Other

- [x] Background color
- [x] Shadow
- [x] Corner radius and smoothing
- [x] Rotate effect
- [x] Border
- [x] Opacity
