### ISSUE TITLE
tracking: Window related features

### ISSUE THREAD

**Issue by marc2332** [marc2332/freya#7]
This tracks multiple features related to the app's windows.

- [x] Custom launch configuration
     - [x] Window size
     - [x] Window title 
     - [x] Window decoration
     - [x] Window transparency
     - [x] Window background color
- [ ] https://github.com/marc2332/freya/issues/44
