### ISSUE TITLE
tracking: Accessibility API

### ISSUE THREAD

**Issue by tropicaaal** [marc2332/freya#844]
- [x] Control over all accessibility node roles, properties, and flags.
    - [x] Basic properties (string, bool, usize, enum) (#882)
    - [x] Node associations (`a11y_named_by`, `a11y_described_by`, `a11y_radio_group`, etc...). Requires some sort of ID system (see below).
    - [x] Control over [screenreader actions](https://docs.rs/accesskit/latest/accesskit/enum.Action.html).
	    - [x] Add builtin actions (this is internally a bitflag, maybe `a11y_actions: "focus, blur, ..."`).
	    - [x] Add [custom actions](https://docs.rs/accesskit/latest/accesskit/struct.CustomAction.html) for screenreaders to announce. (not sure how to represent these as a string for attributes lol)
	    ~~- [ ] Respond to actions (requires a new event on nodes like `onaccessibilityaction`).~~
- [x] Add some sort of ID system or similar for handling accessibility node associations.
- [ ] Measure inline text spans (word measurements, sentence measurements, etc...) and integrate them with AccessKit's APIs. Currently we just add a `name` property to `label`/`paragraph` elements with the inner text of the element, however the ideal way to do this is to have each text span be its own `InlineTextBox` accessibility node.
- [x] Compute intrinsic AccessKit properties from existing attributes such as styles. (#855)
- [x] Uncontrolled accessibility state (default accessibility state for nodes). (#867)
- [x] Incremental accessibility tree (avoid recreating the whole tree every render). (#825)
- [x] Improve focus handling.
	~~- [ ] `onblur`, `onfocus` events.~~
	- [x] Filter non-focusable elements from tab order. (#843)
	- [x] Add and handle `SetSequentialFocusNavigationStartingPoint` and `Blur` actions for focusable nodes.
	- [x] Focus-based keyboard events. (#824)
	- [x] Fix validation of focused element keyboard events (#883).
	- [x] Uncontrolled NodeId generation without the need to use `use_focus`
	- [x] Rename accessibility attributes so they have an a11y prefix. (#869)
	- [x] a11y_autofocus (#878)
	- [x] https://github.com/marc2332/freya/issues/843
- [x] Make `freya_components` accessible and at least on par with ARIA-compliant widgets.

I'm not fully up to date on the state IME support, but anything lacking in that area can also be thrown here.

**Comment by marc2332** [comment]
ALl these things are possible with the changes of https://github.com/marc2332/freya/pull/1351

Only thing missing this deep accessibility for Paragraph

**Comment by marc2332** [comment]
Closing in favor of https://github.com/marc2332/freya/issues/1472
