### ISSUE TITLE
tracking: Text editing

### ISSUE THREAD

**Issue by marc2332** [marc2332/freya#91]
This tracks the current support for different text editing features.

## Supported

- [x] Multi line editing
- [x] Enter key
- [x] Backspace key
- [x] Move cursor to cursor on click
- [x] Move cursor using arrows key
- [ ] Delete key
- [x] Highlight/select text
- [ ] Delete/replace the selected text (https://github.com/marc2332/freya/issues/356)
- [ ] Copy/cut/paste (https://github.com/marc2332/freya/issues/473)
